# Primero cargar datos

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
data=pd.read_csv('train.csv')

data.head()

/Users/iudh/opt/anaconda3/envs/clase/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3172: DtypeWarning: Columns (0,2,22,36,41,45,46,55,61,64,66) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,last_searched,requires_license,region_id,region_name,region_parent_id,region_parent_name,region_parent_parent_id,region_parent_parent_name
0,0,https://www.airbnb.com/rooms/10942766,20211215062351,2021-12-15,B&B La Terrazza Napoli (A’ Chiesa ),Il B&B La Terrazza é un appartamento situato i...,ITALIANO/ENGLISH<br />-Siamo a pochi passi da ...,https://a0.muscache.com/pictures/c13102d9-207b...,54836997.0,https://www.airbnb.com/users/show/54836997,Valentina,2016-01-16,"Naples, Campania, Italy",NaN,within a few hours,100%,100%,f,https://a0.muscache.com/im/pictures/user/074a0...,https://a0.muscache.com/im/pictures/user/074a0...,NaN,4.0,4.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,t,"Napoli, Campania, Italy",Pendino,NaN,40.84824,14.26255,Private room in bed and breakfast,Private room,3.0,NaN,1 private bath,1.0,2.0,"[""Elevator"", ""Essentials"", ""Paid parking off p...",61.0,1.0,28,1.0,1.0,1125.0,1125.0,1.0,1125.0,NaN,t,9.0,36.0,65.0,263.0,2021-12-15,20,1.0,0.0,2016-04-16,2021-06-27,5.00,5.0,5.00,5.00,5.0,4.95,5.0,NaN,t,4.0,0.0,4.0,0.0,0.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,https://www.airbnb.com/rooms/43714230,20211226165759,2021-12-27,Sunlight Maxima Villa Private Pools 24 guests,"Located in Georgioupolis, overlooking the near...","Georgioupolis is Apokoronas, with its pictures...",https://a0.muscache.com/pictures/18b0edf0-f2b9...,345934109.0,https://www.airbnb.com/users/show/345934109,HotelPraxis,2020-05-11,"London, England, United Kingdom",HotelPraxis has already attained the goal of b...,within an hour,100%,99%,t,https://a0.muscache.com/im/pictures/user/0391c...,https://a0.muscache.com/im/pictures/user/0391c...,NaN,0.0,0.0,"['email', 'phone', 'offline_government_id', 's...",t,t,"Georgioupoli, Greece",Αποκορώνου,NaN,35.35024,24.25611,Entire villa,Entire home/apt,16.0,NaN,4 baths,8.0,14.0,"[""Patio or balcony"", ""High chair"", ""Shampoo"", ...",411.0,3.0,1125,3.0,3.0,1125.0,1125.0,3.0,1125.0,NaN,t,0.0,0.0,22.0,210.0,2021-12-27,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,75.0,75.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,https://www.airbnb.com/rooms/11904781,20211208225137,2021-12-09,Mini House. Take a Siesta on the Hammock on th...,"The mini-apartment, completely renovated in 20...",The street where the apartment is located is q...,https://a0.muscache.com/pictures/monet/Select-...,6956810.0,https://www.airbnb.com/users/show/6956810,Nicola,2013-06-17,"Rome, Lazio, Italy","I lived in Sicily, Venice, Sardinia and Triest...",within an hour,100%,100%,t,https://a0.muscache.com/im/users/6956810/profi...,https://a0.muscache.com/im/users/6956810/profi...,San Giovanni,3.0,3.0,"['email', 'phone', 'google', 'reviews', 'jumio...",t,t,"Rome, Lazio, Italy",VII San Giovanni/Cinecittà,NaN,41.87250,12.51873,Tiny house,Entire home/apt,2.0,NaN,1 bath,NaN,1.0,"[""Bathroom essentials"", ""Pack \u2019n play/Tra...",37.0,1.0,28,1.0,4.0,1125.0,1125.0,1.1,1125.0,NaN,t,0.0,19.0,41.0,227.0,2021-12-09,416,53.0,12.0,2016-04-28,2021-12-09,4.93,4.94,4.89,4.95,4.97,4.76,4.92,NaN,t,4.0,4.0,0.0,0.0,6.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,https://www.airbnb.com/rooms/39126878,20211207182322,2021-12-08,Cosy and design flat near Champs-Élysées,Cosy and design flat near Champs-Élysées. Perf...,Nice and safe neighborhood near the Champs-Ély...,https://a0.muscache.com/pictures/e511feba-f934...,20641177.0,https://www.airbnb.com/users/show/20641177,Armand,2014-08-28,"Paris, Île-de-France, France",NaN,NaN,NaN,0%,f,https://a0.muscache.com/im/users/20641177/prof...,https://a0.muscache.com/im/users/20641177/prof...,Ternes,1.0,1.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Paris, Île-de-France, France",Batignolles-Monceau,NaN,48.88298,2.29094,Entire rental unit,Entire home/apt,2.0,NaN,1 bath,1.0,2.0,"[""Washer"", ""Refrigerator"", ""Elevator"", ""Kitche...",131.0,365.0,1125,365.0,365.0,1125.0,1125.0,365.0,1125.0,NaN,t,29.0,59.0,89.0,179.0,2021-12-08,1,0.0,0.0,2019-11-03,2019-11-03,5.00,5.0,5.00,5.00,5.0,5.00,5.0,NaN,f,1.0,1.0,0.0,0.0,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,https://www.airbnb.com/rooms/7553302,20211207182322,2021-12-08,Agréable studio,"7ème, superbe quartier vivant, à 2 pas des com...",NaN,https://a0.muscache.com/pictures/95849745/236e...,18030079.0,https://www.airbnb.com/users/show/18030079,Salomé,2014-07-13,"Paris, Île-de-France, France",Etudiante à paris,NaN,NaN,NaN,f,https://a0.muscache.com/im/users/18030079/prof...,https://a0.muscache.com/im/users/18030079/prof...,Tour Eiffel - Champ de Mars,1.0,1.0,"['email', 'phone', 'reviews']",t,f,NaN,Palais-Bourbon,NaN,48.85629,2.30526,Entire rental unit,Entire home/apt,2.0,NaN,1 bath,NaN,1.0,"[""Washer"", ""Elevator"", ""Kitchen"", ""Heating"", ""...",55.0,365.0,1125,365.0,365.0,1125.0,1125.0,365.0,1125.0,NaN,t,0.0,0.0,0.0,0.0,2021-12-08,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263760 entries, 0 to 263759
Data columns (total 82 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   id                                            263747 non-null  object
 1   listing_url                                   263757 non-null  object
 2   scrape_id                                     263757 non-null  object
 3   last_scraped                                  263758 non-null  object
 4   name                                          263662 non-null  object
 5   description                                   259244 non-null  object
 6   neighborhood_overview                         153845 non-null  object
 7   picture_url                                   263745 non-null  object
 8   host_id                                       263760 non-null  float64
 9   host_url                                      263760 non-null  object
 10  host_name                                     263353 non-null  object
 11  host_since                                    263353 non-null  object
 12  host_location                                 262829 non-null  object
 13  host_about                                    140921 non-null  object
 14  host_response_time                            170986 non-null  object
 15  host_response_rate                            170980 non-null  object
 16  host_acceptance_rate                          186749 non-null  object
 17  host_is_superhost                             263332 non-null  object
 18  host_thumbnail_url                            263332 non-null  object
 19  host_picture_url                              263332 non-null  object
 20  host_neighbourhood                            127322 non-null  object
 21  host_listings_count                           263311 non-null  float64
 22  host_total_listings_count                     263332 non-null  object
 23  host_verifications                            263739 non-null  object
 24  host_has_profile_pic                          263332 non-null  object
 25  host_identity_verified                        263332 non-null  object
 26  neighbourhood                                 153832 non-null  object
 27  neighbourhood_cleansed                        244612 non-null  object
 28  neighbourhood_group_cleansed                  70815 non-null   object
 29  latitude                                      263739 non-null  float64
 30  longitude                                     263739 non-null  float64
 31  property_type                                 263739 non-null  object
 32  room_type                                     263739 non-null  object
 33  accommodates                                  263739 non-null  float64
 34  bathrooms                                     21 non-null      float64
 35  bathrooms_text                                263213 non-null  object
 36  bedrooms                                      244013 non-null  object
 37  beds                                          255998 non-null  float64
 38  amenities                                     263739 non-null  object
 39  price                                         263739 non-null  float64
 40  minimum_nights                                263739 non-null  float64
 41  maximum_nights                                263739 non-null  object
 42  minimum_minimum_nights                        263729 non-null  float64
 43  maximum_minimum_nights                        263729 non-null  float64
 44  minimum_maximum_nights                        263729 non-null  float64
 45  maximum_maximum_nights                        263727 non-null  object
 46  minimum_nights_avg_ntm                        263727 non-null  object
 47  maximum_nights_avg_ntm                        263727 non-null  float64
 48  calendar_updated                              19 non-null      float64
 49  has_availability                              263737 non-null  object
 50  availability_30                               263737 non-null  float64
 51  availability_60                               263737 non-null  float64
 52  availability_90                               263737 non-null  float64
 53  availability_365                              263737 non-null  float64
 54  calendar_last_scraped                         263730 non-null  object
 55  number_of_reviews                             263739 non-null  object
 56  number_of_reviews_ltm                         263739 non-null  float64
 57  number_of_reviews_l30d                        263739 non-null  float64
 58  first_review                                  210522 non-null  object
 59  last_review                                   210522 non-null  object
 60  review_scores_rating                          210520 non-null  float64
 61  review_scores_accuracy                        208088 non-null  object
 62  review_scores_cleanliness                     208112 non-null  float64
 63  review_scores_checkin                         208049 non-null  float64
 64  review_scores_communication                   208091 non-null  object
 65  review_scores_location                        208040 non-null  float64
 66  review_scores_value                           208027 non-null  object
 67  license                                       113305 non-null  object
 68  instant_bookable                              263721 non-null  object
 69  calculated_host_listings_count                263718 non-null  float64
 70  calculated_host_listings_count_entire_homes   263718 non-null  float64
 71  calculated_host_listings_count_private_rooms  263718 non-null  float64
 72  calculated_host_listings_count_shared_rooms   263718 non-null  float64
 73  reviews_per_month                             210501 non-null  float64
 74  last_searched                                 13575 non-null   object
 75  requires_license                              0 non-null       float64
 76  region_id                                     19127 non-null   float64
 77  region_name                                   19127 non-null   object
 78  region_parent_id                              19127 non-null   float64
 79  region_parent_name                            19127 non-null   object
 80  region_parent_parent_id                       19127 non-null   object
 81  region_parent_parent_name                     19127 non-null   object
dtypes: float64(32), object(50)
memory usage: 165.0+ MB

In [4]:
df_numeric=data._get_numeric_data().drop(columns=['host_id', 'bathrooms', 'calendar_updated',
                                       'review_scores_rating', 'review_scores_cleanliness', 
                                       'review_scores_checkin', 'review_scores_location', 
                                       'calculated_host_listings_count', 
                                       'calculated_host_listings_count_entire_homes', 
                                       'calculated_host_listings_count_private_rooms', 
                                       'calculated_host_listings_count_shared_rooms',
                                       'reviews_per_month',
                                       'requires_license','region_id', 'region_parent_id'])

In [5]:
import re

patron='[0-9]+'

def limpieza_ba(x):
    n_ba=0
    
    try:
        n_ba=int(re.findall(patron, x)[0])
    except:
        n_ba=0
        
    return n_ba

data.bathrooms_text.apply(limpieza_ba)[:10]  # cuidao, esto puede estar mal, probable

0    1
1    4
2    1
3    1
4    1
5    3
6    1
7    3
8    1
9    1
Name: bathrooms_text, dtype: int64

In [6]:
df=df_numeric.copy()

df['bathroom']=data.bathrooms_text.apply(limpieza_ba)

In [7]:
df_numeric.head()

,host_listings_count,latitude,longitude,accommodates,beds,price,minimum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews_ltm,number_of_reviews_l30d
0,4.0,40.84824,14.26255,3.0,2.0,61.0,1.0,1.0,1.0,1125.0,1125.0,9.0,36.0,65.0,263.0,1.0,0.0
1,0.0,35.35024,24.25611,16.0,14.0,411.0,3.0,3.0,3.0,1125.0,1125.0,0.0,0.0,22.0,210.0,0.0,0.0
2,3.0,41.87250,12.51873,2.0,1.0,37.0,1.0,1.0,4.0,1125.0,1125.0,0.0,19.0,41.0,227.0,53.0,12.0
3,1.0,48.88298,2.29094,2.0,2.0,131.0,365.0,365.0,365.0,1125.0,1125.0,29.0,59.0,89.0,179.0,0.0,0.0
4,1.0,48.85629,2.30526,2.0,1.0,55.0,365.0,365.0,365.0,1125.0,1125.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df['cats']=data.host_verifications

df=df.dropna()

In [9]:
def limpieza_cats(x):
    
    return str(x).replace('[', '').replace(']', '').replace("'", '').split(',')

df.cats=df.cats.apply(limpieza_cats)

In [10]:
df.cats=df.cats.apply(lambda x: x[0])

In [11]:
df.head()

,host_listings_count,latitude,longitude,accommodates,beds,price,minimum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews_ltm,number_of_reviews_l30d,bathroom,cats
0,4.0,40.84824,14.26255,3.0,2.0,61.0,1.0,1.0,1.0,1125.0,1125.0,9.0,36.0,65.0,263.0,1.0,0.0,1,email
1,0.0,35.35024,24.25611,16.0,14.0,411.0,3.0,3.0,3.0,1125.0,1125.0,0.0,0.0,22.0,210.0,0.0,0.0,4,email
2,3.0,41.87250,12.51873,2.0,1.0,37.0,1.0,1.0,4.0,1125.0,1125.0,0.0,19.0,41.0,227.0,53.0,12.0,1,email
3,1.0,48.88298,2.29094,2.0,2.0,131.0,365.0,365.0,365.0,1125.0,1125.0,29.0,59.0,89.0,179.0,0.0,0.0,1,email
4,1.0,48.85629,2.30526,2.0,1.0,55.0,365.0,365.0,365.0,1125.0,1125.0,0.0,0.0,0.0,0.0,0.0,0.0,1,email

In [12]:
df=df.reset_index(drop=True)

df.head()

,host_listings_count,latitude,longitude,accommodates,beds,price,minimum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews_ltm,number_of_reviews_l30d,bathroom,cats
0,4.0,40.84824,14.26255,3.0,2.0,61.0,1.0,1.0,1.0,1125.0,1125.0,9.0,36.0,65.0,263.0,1.0,0.0,1,email
1,0.0,35.35024,24.25611,16.0,14.0,411.0,3.0,3.0,3.0,1125.0,1125.0,0.0,0.0,22.0,210.0,0.0,0.0,4,email
2,3.0,41.87250,12.51873,2.0,1.0,37.0,1.0,1.0,4.0,1125.0,1125.0,0.0,19.0,41.0,227.0,53.0,12.0,1,email
3,1.0,48.88298,2.29094,2.0,2.0,131.0,365.0,365.0,365.0,1125.0,1125.0,29.0,59.0,89.0,179.0,0.0,0.0,1,email
4,1.0,48.85629,2.30526,2.0,1.0,55.0,365.0,365.0,365.0,1125.0,1125.0,0.0,0.0,0.0,0.0,0.0,0.0,1,email

In [13]:
df=pd.concat([df, pd.get_dummies(df.cats).reset_index(drop=True)], axis=1)

df.head()

,host_listings_count,latitude,longitude,accommodates,beds,price,minimum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews_ltm,number_of_reviews_l30d,bathroom,cats,,email,facebook,google,jumio,manual_online,offline_government_id,phone,reviews
0,4.0,40.84824,14.26255,3.0,2.0,61.0,1.0,1.0,1.0,1125.0,1125.0,9.0,36.0,65.0,263.0,1.0,0.0,1,email,0,1,0,0,0,0,0,0,0
1,0.0,35.35024,24.25611,16.0,14.0,411.0,3.0,3.0,3.0,1125.0,1125.0,0.0,0.0,22.0,210.0,0.0,0.0,4,email,0,1,0,0,0,0,0,0,0
2,3.0,41.87250,12.51873,2.0,1.0,37.0,1.0,1.0,4.0,1125.0,1125.0,0.0,19.0,41.0,227.0,53.0,12.0,1,email,0,1,0,0,0,0,0,0,0
3,1.0,48.88298,2.29094,2.0,2.0,131.0,365.0,365.0,365.0,1125.0,1125.0,29.0,59.0,89.0,179.0,0.0,0.0,1,email,0,1,0,0,0,0,0,0,0
4,1.0,48.85629,2.30526,2.0,1.0,55.0,365.0,365.0,365.0,1125.0,1125.0,0.0,0.0,0.0,0.0,0.0,0.0,1,email,0,1,0,0,0,0,0,0,0

In [14]:
df=df.drop('cats', axis=1)

df.head()

,host_listings_count,latitude,longitude,accommodates,beds,price,minimum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews_ltm,number_of_reviews_l30d,bathroom,,email,facebook,google,jumio,manual_online,offline_government_id,phone,reviews
0,4.0,40.84824,14.26255,3.0,2.0,61.0,1.0,1.0,1.0,1125.0,1125.0,9.0,36.0,65.0,263.0,1.0,0.0,1,0,1,0,0,0,0,0,0,0
1,0.0,35.35024,24.25611,16.0,14.0,411.0,3.0,3.0,3.0,1125.0,1125.0,0.0,0.0,22.0,210.0,0.0,0.0,4,0,1,0,0,0,0,0,0,0
2,3.0,41.87250,12.51873,2.0,1.0,37.0,1.0,1.0,4.0,1125.0,1125.0,0.0,19.0,41.0,227.0,53.0,12.0,1,0,1,0,0,0,0,0,0,0
3,1.0,48.88298,2.29094,2.0,2.0,131.0,365.0,365.0,365.0,1125.0,1125.0,29.0,59.0,89.0,179.0,0.0,0.0,1,0,1,0,0,0,0,0,0,0
4,1.0,48.85629,2.30526,2.0,1.0,55.0,365.0,365.0,365.0,1125.0,1125.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1,0,0,0,0,0,0,0

# Guardar toda la transformacion en una funcion, para el test

In [15]:
# funciones auxiliares

patron='[0-9]+'

def limpieza_ba(x):
    n_ba=0
    
    try:
        n_ba=int(re.findall(patron, x)[0])
    except:
        n_ba=0
        
    return n_ba



def limpieza_cats(x):
    
    return str(x).replace('[', '').replace(']', '').replace("'", '').split(',')

In [29]:
def limpieza_dataset(df):
    
    df_numeric=df._get_numeric_data().drop(columns=['host_id', 'bathrooms', 'calendar_updated',
                                       'review_scores_rating', 'review_scores_cleanliness', 
                                       'review_scores_checkin', 'review_scores_location', 
                                       'calculated_host_listings_count', 
                                       'calculated_host_listings_count_entire_homes', 
                                       'calculated_host_listings_count_private_rooms', 
                                       'calculated_host_listings_count_shared_rooms',
                                       'reviews_per_month',
                                       'requires_license','region_id', 'region_parent_id'])
    
    n_df=df_numeric.copy()

    n_df['bathroom']=df.bathrooms_text.apply(limpieza_ba)
    
    n_df['cats']=df.host_verifications

    #n_df=n_df.dropna() # cuidado, esto con el test no, porque no se pueden quitar filas
    
    n_df.cats=n_df.cats.apply(limpieza_cats)
    
    n_df.cats=n_df.cats.apply(lambda x: x[0])
    
    n_df=n_df.reset_index(drop=True)
    
    n_df=pd.concat([n_df, pd.get_dummies(n_df.cats).reset_index(drop=True)], axis=1)
    
    n_df=n_df.drop('cats', axis=1)
    
    return n_df

In [17]:
df.shape

(255578, 27)

In [18]:
limpieza_dataset(data).shape

(255578, 27)

In [19]:
df.head()

,host_listings_count,latitude,longitude,accommodates,beds,price,minimum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews_ltm,number_of_reviews_l30d,bathroom,,email,facebook,google,jumio,manual_online,offline_government_id,phone,reviews
0,4.0,40.84824,14.26255,3.0,2.0,61.0,1.0,1.0,1.0,1125.0,1125.0,9.0,36.0,65.0,263.0,1.0,0.0,1,0,1,0,0,0,0,0,0,0
1,0.0,35.35024,24.25611,16.0,14.0,411.0,3.0,3.0,3.0,1125.0,1125.0,0.0,0.0,22.0,210.0,0.0,0.0,4,0,1,0,0,0,0,0,0,0
2,3.0,41.87250,12.51873,2.0,1.0,37.0,1.0,1.0,4.0,1125.0,1125.0,0.0,19.0,41.0,227.0,53.0,12.0,1,0,1,0,0,0,0,0,0,0
3,1.0,48.88298,2.29094,2.0,2.0,131.0,365.0,365.0,365.0,1125.0,1125.0,29.0,59.0,89.0,179.0,0.0,0.0,1,0,1,0,0,0,0,0,0,0
4,1.0,48.85629,2.30526,2.0,1.0,55.0,365.0,365.0,365.0,1125.0,1125.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1,0,0,0,0,0,0,0

### A partir de aqui, modelado

In [20]:
from sklearn.model_selection import train_test_split as tts

In [21]:
X=df.drop('price', axis=1)
y=df.price

In [22]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.15, random_state=42)

In [23]:
# modelo

from sklearn.ensemble import RandomForestRegressor as RFR

In [24]:
modelo=RFR()

modelo.fit(X_train, y_train)

RandomForestRegressor()

**evaluacion**

In [25]:
modelo.score(X_test, y_test)# R2

0.22926770783002448

In [27]:
y_pred=modelo.predict(X_test)

In [26]:
from sklearn.metrics import mean_squared_error as mse

In [28]:
mse(y_pred, y_test, squared=False) # rmse

702.8671367618317

### A partir de aqui, minimizar rmse, toqueteando lo que seya.

#### luego reentrenar con todos los datos y hacer prediccion sobre test.csv

In [30]:
X.shape

(255578, 26)

In [128]:
new_data=pd.read_csv('test.csv')

new_data=limpieza_dataset(new_data)

new_data=new_data.drop(columns=['maximum_nights', 'work_email', 'None', 'bedrooms','number_of_reviews', 'nan', 'jumio','offline_government_id',
                                'id', 'scrape_id', 'review_scores_accuracy', 'review_scores_communication', 
                                'review_scores_value', 'host_total_listings_count'])

new_data=new_data.fillna(0)

new_data.shape # deberian ser mismas columnas que X

(87913, 26)

In [131]:
y_pred=modelo.predict(new_data)

In [132]:
y_pred.shape

(87913,)

In [133]:
sample_df=pd.DataFrame()


sample_df['id']=[str(i) for i in range(len(y_pred))]
sample_df['price']=y_pred

sample_df.shape

(87913, 2)

In [134]:
sample_df.head()

  id   price
0  0  247.50
1  1   58.77
2  2  548.96
3  3  175.49
4  4   64.96

In [135]:
sample_df.to_csv('prediccion.csv', index=False, header=True)

In [136]:
n_d=pd.read_csv('test.csv')

In [137]:
#n_d=n_d.dropna(subset=['id']).reset_index(drop=True)

n_d.shape

(87913, 81)

In [98]:
n_d=n_d[~(n_d.id=='who likes to chat with guests.')]
n_d=n_d[~(n_d.id=='I am a Bundoranian. Come visit my beautiful town and take in the sea air. !')]

n_d=n_d.reset_index(drop=True)

In [108]:
n_d.to_csv('test.csv', index=False)